### ISSUE TITLE
Wrong Summary for Fontset metainfo

### ISSUE THREAD

**Issue by StefanBruens** [ArtifexSoftware/urw-base35-fonts#21]
https://github.com/ArtifexSoftware/urw-base35-fonts/blob/d11c5ea1d74846f3652b1b8ae14a09a724f99ee9/appstream/de.urwpp.URWCoreFontSetLevel2.metainfo.xml#L16

**Comment by fabiangreffrath** [comment]
@deekej After so many metadata fixes, maybe it's time to push a new release?

**Comment by deekej** [comment]
@fabiangreffrath Unfortunately, it's not a time yet for it...

1) We are currently waiting for fixes from _(URW)++_ for OTF versions of fonts. Many of them have missing or wrong charmaps/glyhps.      
2) The new releases are tight to new releases from _(URW)++_, because of the versioning issues they have introduced before.
3) And also, AFAICT, the new releases are also tight to new releases of Ghostscript.

The new Ghostscript is coming soon in March IIRC, so lets hope the _(URW)++_ fixes it before then. :)

**Comment by fabiangreffrath** [comment]
Apparently, the fonts have not been updated since then, but nevertheless it would be nice to have a new release of this repo tagged which includes all the recent metadata fixes. I understand that you don't want to name it after the current date, as this would probably imply that the fonts have been changed, but maybe a versioning like e.g. `20170801a` would be acceptable?

**Comment by deekej** [comment]
I would prefer the `20170801.1` instead, but I guess the `20170801a` would be okay as well. And I will ping upstream to see what the status of the fixes to OTF versions. :)
